import { PrismaClient } from '@prisma/client'
import { resolve } from 'path'

// Fix: Force PostgreSQL URL when env has been overridden to SQLite path
// (some environments set DATABASE_URL to a SQLite file path which breaks the postgresql provider)
function getDatabaseUrl(): string | undefined {
  const envUrl = process.env.DATABASE_URL
  if (envUrl && envUrl.startsWith('postgresql://')) {
    return envUrl
  }
  // Fallback to the configured PostgreSQL Supabase URL
  // This ensures the app works even when DATABASE_URL is incorrectly set
  return 'postgresql://postgres.liwxrnvaycudbxpfoiam:Giov%401234200@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true'
}

/**
 * Cache-bust key for the global Prisma client. Bump this whenever the
 * Prisma schema gains new fields, so the dev server's HMR-cached client
 * is replaced with a fresh one that knows about the new columns.
 *
 * We also use a versioned GLOBAL KEY so that older HMR-cached modules
 * (which wrote to the unversioned `prisma` key) cannot accidentally
 * reuse a stale client. Changing the key forces a fresh PrismaClient
 * to be constructed even if the cache-version check itself was skipped
 * during a partial HMR reload.
 */
const PRISMA_CACHE_VERSION = 'f6-social-v2-2025'
const PRISMA_GLOBAL_KEY = `prisma_${PRISMA_CACHE_VERSION}`

interface GlobalWithPrisma {
  [key: string]: PrismaClient | string | undefined
}

const globalForPrisma = globalThis as unknown as GlobalWithPrisma

function createPrismaClient(): PrismaClient {
  const url = getDatabaseUrl()
  // Set the env vars so Prisma client picks them up at construction
  if (url) {
    process.env.DATABASE_URL = url
    process.env.DIRECT_URL = process.env.DIRECT_URL?.startsWith('postgresql://')
      ? process.env.DIRECT_URL
      : 'postgresql://postgres.liwxrnvaycudbxpfoiam:Giov%401234200@aws-0-eu-west-1.pooler.supabase.com:5432/postgres'
  }
  // Construct a fresh PrismaClient. Turbopack/Next.js HMR caches modules,
  // so we always re-import @prisma/client here to make sure we get the
  // version that matches the current schema (after `prisma generate`).
  //
  // When `prisma generate` regenerates @prisma/client (e.g. after `prisma db push`
  // adds a new model), the dev server needs a restart to fully pick up the new
  // client. The cache-version bump above ensures a brand-new PrismaClient instance
  // is constructed (rather than reusing the old one from the previous cache key),
  // and the require('@prisma/client') call below picks up whatever @prisma/client
  // is currently on disk.
  //
  // As a fallback (added in F4) we also try loading the freshly-generated client
  // directly via its absolute path. Turbopack sometimes caches the OLD
  // @prisma/client module even after `prisma generate` writes new files to
  // node_modules/.prisma/client/. Loading via Node's native `require` (bypassing
  // Turbopack's module interception with `eval`) ensures we get the on-disk
  // version every time.
  //
  // In F6 we additionally invalidate Node's native require cache for the
  // .prisma/client entry before re-requiring it — that way the running dev
  // server picks up newly-added models (StudyGroup, Event, Article) without
  // needing a manual `bun run dev` restart.
  let FreshPrismaClientCtor: new () => PrismaClient;
  try {
    // Primary path: bypass Turbopack by using Node's native require via eval.
    // The string literal `require` here is not statically analyzable by
    // Turbopack, so it falls through to Node's runtime require, which always
    // re-reads the file from disk.
    const nativeRequire = eval('require') as NodeRequire;
    const prismaClientPath = resolve(
      process.cwd(),
      'node_modules/.prisma/client/index.js'
    );
    // Bust Node's require cache so we always get the on-disk version (which
    // may have been regenerated by `prisma generate` since the dev server
    // started). This is safe — the new module is loaded immediately after.
    delete nativeRequire.cache[prismaClientPath];
    // Also clear any internal relative imports the .prisma/client/index.js
    // may have done (e.g. ./runtime, ./schema). Walk the cache and drop entries
    // that live under the .prisma/client folder.
    for (const key of Object.keys(nativeRequire.cache)) {
      if (key.includes('/node_modules/.prisma/client/')) {
        delete nativeRequire.cache[key];
      }
    }
    const mod = nativeRequire(prismaClientPath) as {
      PrismaClient: new () => PrismaClient;
    };
    FreshPrismaClientCtor = mod.PrismaClient;
  } catch {
    // Fallback: regular @prisma/client resolution (Turbopack-cached).
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const mod = require('@prisma/client') as {
      PrismaClient: new () => PrismaClient;
    };
    FreshPrismaClientCtor = mod.PrismaClient;
  }
  return new FreshPrismaClientCtor();
}

// Look for a previously-cached client under the versioned key.
const cachedClient = globalForPrisma[PRISMA_GLOBAL_KEY] as PrismaClient | undefined

export const db = cachedClient ?? createPrismaClient()

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma[PRISMA_GLOBAL_KEY] = db
  // Also write the legacy unversioned key for backwards compatibility
  // (older HMR-cached modules may still read from `globalForPrisma.prisma`).
  globalForPrisma.prisma = db
  globalForPrisma.__prismaCacheVersion = PRISMA_CACHE_VERSION
}
