"""
Définit les métadonnées de toutes les banques (39 au total).
"""
import json, os

BANKS_DIR = "/home/z/my-project/scripts/generated/banks"
os.makedirs(BANKS_DIR, exist_ok=True)

BANKS = [
    # === Culture Générale ===
    {"bankKey": "culture-bf", "title": "Culture Générale - Burkina Faso", "description": "Histoire, géographie, institutions et culture du Burkina Faso.", "category": "Culture Générale", "subcategory": "Burkina Faso", "icon": "Landmark", "color": "emerald", "level": "TOUS", "subject": "Culture générale du Burkina Faso: institutions (président Ibrahim Traoré, ALT présidée par Ousmane Bougma), histoire (Thomas Sankara, indépendance 1960), géographie (17 régions, 47 provinces), FESPACO, SIAO, SNC, AES"},
    {"bankKey": "culture-bf-2025", "title": "Culture Générale - Concours 2025", "description": "Questions actualisées 2025 : institutions, politique, culture et actualité du Burkina Faso.", "category": "Culture Générale", "subcategory": "Concours 2025", "icon": "Sparkles", "color": "rose", "level": "TOUS", "subject": "Culture générale concours 2025: institutions (Ibrahim Traoré, Ousmane Bougma, AES), événements récents (FSP, Sotigui Awards, SOBTO), politique, dates clés 2024-2025"},
    {"bankKey": "culture-generale-diverse", "title": "Questions Diverses - Culture Générale", "description": "Questions de culture générale couvrant l'histoire, la géographie, les institutions.", "category": "Culture Générale", "subcategory": "Divers", "icon": "BadgeCheck", "color": "teal", "level": "TOUS", "subject": "Culture générale diverse: histoire mondiale, géographie, institutions internationales, ONU, UNESCO, CEDEAO, personnalités, dates clés"},
    {"bankKey": "actualite-mondiale", "title": "Actualité Mondiale 2024-2025", "description": "Événements récents, conflits, institutions, personnalités.", "category": "Culture Générale", "subcategory": "Actualité", "icon": "Newspaper", "color": "emerald", "level": "TOUS", "subject": "Actualité mondiale 2024-2025: Russie-Ukraine, Israël-Hamas, AES, Ibrahim Traoré, Trump 47e président, IA, COP, CEDEAO"},
    {"bankKey": "histoire-monde", "title": "Histoire du Monde", "description": "Grandes périodes, civilisations, révolutions, guerres mondiales.", "category": "Culture Générale", "subcategory": "Histoire du Monde", "icon": "Globe2", "color": "amber", "level": "TOUS", "subject": "Histoire du monde: Antiquité, Moyen Âge, Renaissance, Révolution française, Guerres mondiales, Guerre froide, décolonisation, mur de Berlin"},
    {"bankKey": "culture-generale-monde", "title": "Culture Générale du Monde", "description": "Géographie, capitales, fleuves, montagnes, arts, littérature, religions.", "category": "Culture Générale", "subcategory": "Culture du Monde", "icon": "Globe2", "color": "teal", "level": "TOUS", "subject": "Culture générale du monde: capitales, fleuves, montagnes, déserts, océans, religions, arts, littérature, prix Nobel, institutions"},
    {"bankKey": "diplomatie-mondiale", "title": "Diplomatie et Relations Internationales", "description": "Diplomatie, traités, organisations, droit international.", "category": "Culture Générale", "subcategory": "Diplomatie", "icon": "Handshake", "color": "violet", "level": "TOUS", "subject": "Diplomatie: traités (Westphalie, Vienne, Versailles), droit international, ONU, UA, CEDEAO, AES, UE, négociations, ambassades"},
    {"bankKey": "mpsr2-faits", "title": "Faits Marquants du MPSR 2", "description": "Transition politique au Burkina Faso, actions du MPSR 2.", "category": "Culture Générale", "subcategory": "MPSR 2", "icon": "Landmark", "color": "emerald", "level": "TOUS", "subject": "MPSR 2: Ibrahim Traoré 30 sept 2022, AES 16 sept 2023, Confédération 9 juil 2024, FSP 23 jan 2023, ALT Ousmane Bougma 11 nov 2022, retrait CEDEAO"},

    # === Psychotechnique ===
    {"bankKey": "psycho-logique", "title": "Tests Psychotechniques - Logique & Suites", "description": "Suites numériques, séries logiques, codes et raisonnement.", "category": "Psychotechnique", "subcategory": "Logique", "icon": "Brain", "color": "violet", "level": "TOUS", "subject": "Tests psychotechniques: suites numériques, séries alphabétiques, logique, codes, raisonnement, Fibonacci, carrés, cubes"},
    {"bankKey": "psycho-vocabulaire", "title": "Tests Psychotechniques - Vocabulaire & Orthographe", "description": "Synonymes, orthographe, accords et vocabulaire français.", "category": "Psychotechnique", "subcategory": "Vocabulaire", "icon": "SpellCheck", "color": "amber", "level": "TOUS", "subject": "Vocabulaire et orthographe: synonymes, antonymes, accords, conjugaison, orthographe correcte, expressions françaises"},

    # === Secondaire ===
    {"bankKey": "math-college", "title": "Mathématiques - Collège (6e à 3e)", "description": "Nombres, calcul, géométrie de base, fractions, équations.", "category": "Secondaire", "subcategory": "Mathématiques", "icon": "Calculator", "color": "emerald", "level": "COLLEGE", "subject": "Mathématiques collège: nombres, fractions, équations, géométrie, Pythagore, Thalès, proportionnalité, pourcentages"},
    {"bankKey": "math-lycee", "title": "Mathématiques - Lycée (2nde à Terminale)", "description": "Fonctions, suites, trigonométrie, probabilités, dérivées.", "category": "Secondaire", "subcategory": "Mathématiques", "icon": "Sigma", "color": "teal", "level": "LYCEE", "subject": "Mathématiques lycée: fonctions, dérivées, intégrales, suites, trigonométrie, nombres complexes, probabilités, logarithmes"},
    {"bankKey": "physique-chimie-lycee", "title": "Physique-Chimie - Lycée", "description": "Mécanique, électricité, optique, chimie organique et minérale.", "category": "Secondaire", "subcategory": "Physique-Chimie", "icon": "Atom", "color": "sky", "level": "LYCEE", "subject": "Physique-chimie lycée: mécanique, électricité, optique, chimie organique, acide-base, oxydoréduction, réactions"},
    {"bankKey": "svt-lycee", "title": "Sciences de la Vie et de la Terre (SVT) - Lycée", "description": "Génétique, immunité, géologie, écologie, reproduction.", "category": "Secondaire", "subcategory": "SVT", "icon": "Dna", "color": "rose", "level": "LYCEE", "subject": "SVT lycée: génétique, ADN, immunologie, géologie, plaques tectoniques, écologie, reproduction, photosynthèse"},
    {"bankKey": "svt-6e-termd", "title": "SVT - Du 6e à Terminale D", "description": "Biologie, géologie, écologie - programme complet.", "category": "Secondaire", "subcategory": "SVT", "icon": "Dna", "color": "rose", "level": "LYCEE", "subject": "SVT du 6e à Terminale D: cellule, reproduction, génétique, immunologie, géologie, écologie, nutrition, santé (paludisme, VIH)"},
    {"bankKey": "philo-terminale", "title": "Philosophie - Terminale", "description": "Grands courants, auteurs, concepts clés.", "category": "Secondaire", "subcategory": "Philosophie", "icon": "Brain", "color": "violet", "level": "TERM", "subject": "Philosophie: Platon, Aristote, Descartes, Kant, Rousseau, Nietzsche, Sartre, existentialisme, moral, politique, métaphysique"},
    {"bankKey": "francais", "title": "Français & Littérature", "description": "Littérature, grammaire, figures de style.", "category": "Secondaire", "subcategory": "Français", "icon": "BookMarked", "color": "teal", "level": "LYCEE", "subject": "Français et littérature: courants littéraires, grammaire, figures de style, œuvres africaines et françaises, accords, conjugaison"},
    {"bankKey": "geographie", "title": "Géographie & Sciences de la Terre", "description": "Géographie physique et humaine, sciences de la Terre.", "category": "Secondaire", "subcategory": "Géographie", "icon": "Mountain", "color": "sky", "level": "TOUS", "subject": "Géographie: continents, océans, montagnes, déserts, fleuves, capitales, Burkina Faso (17 régions, 47 provinces), climat"},

    # === Universitaire ===
    {"bankKey": "info-algorithmique", "title": "Informatique - Algorithmique", "description": "Structures de données, tris, complexité, récursivité.", "category": "Universitaire", "subcategory": "Informatique", "icon": "Binary", "color": "violet", "level": "LICENCE", "subject": "Algorithmique: structures de données (pile, file, arbre, graphe), tris, recherche, complexité, récursivité, Dijkstra, BFS, DFS"},
    {"bankKey": "info-python", "title": "Informatique - Programmation Python", "description": "Syntaxe Python, types, fonctions, POO.", "category": "Universitaire", "subcategory": "Informatique", "icon": "Code", "color": "amber", "level": "LICENCE", "subject": "Python: types, structures de contrôle, fonctions, POO, listes, dictionnaires, comprehensions, lambda, modules, fichiers"},
    {"bankKey": "info-bdd", "title": "Informatique - Bases de Données & SQL", "description": "Modèle relationnel, SQL, normalisation, jointures.", "category": "Universitaire", "subcategory": "Informatique", "icon": "Database", "color": "cyan", "level": "LICENCE", "subject": "Bases de données: SQL (SELECT, INSERT, UPDATE, DELETE), jointures, normalisation, transactions, ACID, index, SGBD"},
    {"bankKey": "math-analyse", "title": "Mathématiques - Analyse (Licence)", "description": "Limites, continuité, dérivées, intégrales, séries.", "category": "Universitaire", "subcategory": "Mathématiques", "icon": "LineChart", "color": "teal", "level": "LICENCE", "subject": "Analyse: limites, continuité, dérivées, intégrales, suites et séries, équations différentielles, Taylor, Rolle, accroissements finis"},
    {"bankKey": "math-proba-stats", "title": "Mathématiques - Probabilités & Statistiques", "description": "Probabilités, variables aléatoires, lois, estimation.", "category": "Universitaire", "subcategory": "Mathématiques", "icon": "Dice5", "color": "rose", "level": "LICENCE", "subject": "Probabilités et statistiques: lois (binomiale, normale, Poisson), espérance, variance, tests d'hypothèses, estimation, régression"},
    {"bankKey": "sciences-eco-gestion", "title": "Sciences Économiques et de Gestion", "description": "Microéconomie, macroéconomie, comptabilité, marketing.", "category": "Universitaire", "subcategory": "Sciences Économiques", "icon": "TrendingUp", "color": "cyan", "level": "LICENCE", "subject": "Sciences économiques: microéconomie, macroéconomie, comptabilité, gestion, marketing, finance d'entreprise"},
    {"bankKey": "grh", "title": "Gestion des Ressources Humaines (GRH)", "description": "Recrutement, formation, évaluation, paie, droit du travail.", "category": "Universitaire", "subcategory": "Gestion RH", "icon": "Users", "color": "teal", "level": "LICENCE", "subject": "GRH: recrutement, formation, évaluation, paie, droit du travail, relations sociales, GPEC, motivation, leadership"},
    {"bankKey": "statistique", "title": "Statistique Appliquée", "description": "Statistiques descriptives, inférentielles, tests.", "category": "Universitaire", "subcategory": "Statistique", "icon": "BarChart3", "color": "violet", "level": "LICENCE", "subject": "Statistique: descriptive, inférentielle, échantillonnage, tests (Student, Khi-deux), régression, corrélation, variance"},
    {"bankKey": "reseau-telecom", "title": "Réseau et Télécommunications", "description": "Modèles OSI/TCP-IP, routage, protocoles, réseau mobile.", "category": "Universitaire", "subcategory": "Réseau & Télécom", "icon": "Network", "color": "sky", "level": "LICENCE", "subject": "Réseau et télécom: OSI, TCP/IP, IPv4/IPv6, routage, protocoles (HTTP, DNS, DHCP), 4G/5G, fibre, Wi-Fi, VLAN, VPN"},
    {"bankKey": "securite-informatique", "title": "Sécurité Informatique", "description": "Cryptographie, attaques, défenses, audit.", "category": "Universitaire", "subcategory": "Sécurité", "icon": "Shield", "color": "rose", "level": "LICENCE", "subject": "Sécurité: CIA, cryptographie (AES, RSA, SHA), attaques (phishing, SQL injection, XSS, DDoS), firewall, VPN, ISO 27001, OWASP"},
    {"bankKey": "histoire-archeologie", "title": "Histoire et Archéologie", "description": "Histoire ancienne, archéologie africaine, civilisations.", "category": "Universitaire", "subcategory": "Histoire & Archéologie", "icon": "Landmark", "color": "amber", "level": "LICENCE", "subject": "Histoire et archéologie: préhistoire, civilisations anciennes, archéologie africaine, sites du Burkina Faso (Loropéni), UNESCO"},

    # === Concours ===
    {"bankKey": "concours-sante-social", "title": "Concours Santé, Action Sociale & Genre", "description": "Santé publique, action sociale, genre, droits humains.", "category": "Concours", "subcategory": "Santé & Social", "icon": "HeartPulse", "color": "rose", "level": "LICENCE", "subject": "Santé, action sociale et genre: OMS, VIH/sida, paludisme, vaccination, ODD, VBG, équité genre, planning familial, IEC"},
    {"bankKey": "concours-admin-justice", "title": "Concours Administration Générale & Justice", "description": "Droit constitutionnel, administratif, organisation administrative.", "category": "Concours", "subcategory": "Administration & Justice", "icon": "Scale", "color": "emerald", "level": "LICENCE", "subject": "Administration et justice: Constitution 1991, décentralisation (17 régions, 47 provinces), Conseil constitutionnel, Cour des comptes, ENAM"},
    {"bankKey": "concours-developpement-rural", "title": "Concours Développement Rural & Agronomie", "description": "Agriculture, élevage, environnement.", "category": "Concours", "subcategory": "Développement Rural", "icon": "Wheat", "color": "amber", "level": "LICENCE", "subject": "Développement rural: agriculture, élevage, zaï, agroforesterie, barrages, coton, sorgho, changement climatique, biodiversité"},
    {"bankKey": "concours-btp-securite", "title": "Concours BTP & Sécurité", "description": "Bâtiment, génie civil, travaux publics, sécurité.", "category": "Concours", "subcategory": "BTP & Sécurité", "icon": "HardHat", "color": "sky", "level": "LICENCE", "subject": "BTP et sécurité: béton armé, résistance des matériaux, fondations, EPI, sécurité chantier, topographie, loi de Blondel"},
    {"bankKey": "concours-economie-finance", "title": "Concours Économie, Statistiques & Finance", "description": "Économie, statistiques, finance publique, monnaie.", "category": "Concours", "subcategory": "Économie & Finance", "icon": "TrendingUp", "color": "cyan", "level": "LICENCE", "subject": "Économie et finance: PIB, inflation, BCEAO, FCFA, TVA, balance commerciale, marché monétaire, actions, obligations, FMI"},
    {"bankKey": "concours-numerique-medias", "title": "Concours Numérique, Médias & Culture", "description": "TIC, communication, médias, droit de la communication.", "category": "Concours", "subcategory": "Numérique & Médias", "icon": "Radio", "color": "violet", "level": "LICENCE", "subject": "Numérique et médias: TIC, HTML, HTTP, ARPT, liberté de presse, FESPACO, SIAO, fake news, RGPD, IA, big data, cloud"},
    {"bankKey": "concours-education-formation", "title": "Concours Éducation & Formation", "description": "Pédagogie, didactique, psychologie de l'éducation.", "category": "Concours", "subcategory": "Éducation", "icon": "GraduationCap", "color": "emerald", "level": "LICENCE", "subject": "Éducation: pédagogie, Piaget, Vygotski, Gardner, Bloom, évaluation formative/sommative, differentiated, classe inversée"},
    {"bankKey": "concours-informatique-licence", "title": "Concours Informatique - Licence", "description": "Concours niveau licence en informatique.", "category": "Concours", "subcategory": "Informatique", "icon": "Cpu", "color": "violet", "level": "LICENCE", "subject": "Informatique licence: RAM, ROM, IP, ports, OSI, TCP/UDP, Linux, Git, POO, MVC, langages (C, Java, Python, JavaScript)"},
    {"bankKey": "economie", "title": "Économie & Développement Durable", "description": "Économie générale, politique économique, développement durable.", "category": "Culture Générale", "subcategory": "Économie", "icon": "TrendingUp", "color": "cyan", "level": "TOUS", "subject": "Économie et développement durable: PIB, inflation, politique monétaire, croissance endogène, soutenabilité, taxe carbone, biens communs"},
]

for bank in BANKS:
    path = os.path.join(BANKS_DIR, f"{bank['bankKey']}.json")
    if os.path.exists(path):
        existing = json.load(open(path))
        for k in ["title", "description", "category", "subcategory", "icon", "color", "level"]:
            if k in bank:
                existing[k] = bank[k]
        with open(path, 'w') as f:
            json.dump(existing, f, ensure_ascii=False, indent=2)
    else:
        bank["questions"] = []
        with open(path, 'w') as f:
            json.dump(bank, f, ensure_ascii=False, indent=2)

print(f"{len(BANKS)} banks defined/updated")
